clusters:
- name: minikube
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheusOperator:
      enabled: true
      version: "8.3.3"

    sampleApp:
      enabled: true
      serviceType: NodePort
      branch: showandtell

- name: gke
  destinationServer: 
  apps:
    prometheusOperator:
      enabled: true
      version: "8.3.3"

    sampleApp:
      enabled: true
      serviceType: NodePort
      branch: showandtell