{{- range .Values.clusters }}
{{- if .apps.prometheusOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "monitoring"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .destinationServer }}
  project: default
  source:
    chart: prometheus-operator
    repoURL: https://kubernetes-charts.storage.googleapis.com
    targetRevision: {{ .apps.prometheusOperator.version }}
{{- end }}
---
{{- end }}