{{- range .Values.clusters }}
{{- if .apps.sampleApp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "sample"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .destinationServer }}
  project: default
  source:
    path: .
    repoURL: 'https://github.com/kanuahs/flask-sample-chart.git'
    targetRevision: {{ .apps.sampleApp.branch }}
    helm:
      parameters:
        - name: service.type
          value: {{ .apps.sampleApp.serviceType }}
{{- end }}
---

{{- end }}